replicaCount: 1

image:
  repository: your-dockerhub-username/docker-pipeline-demo
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: myapp.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

config:
  ENV: development
  DEBUG: "true"

resources: {}
